"""
Fail-Safe Supervisor System
Real-time monitoring and safety checks for PG-ES optimization
"""

import numpy as np
import logging
import time
from typing import Dict, List, Tuple, Optional, Any
from dataclasses import dataclass, field
from enum import Enum
import json
import warnings

class AlertLevel(Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    EMERGENCY = "EMERGENCY"

@dataclass
class SupervisorAlert:
    """Alert generated by supervisor system"""
    timestamp: float
    level: AlertLevel
    category: str
    message: str
    data: Dict[str, Any] = field(default_factory=dict)
    requires_intervention: bool = False

class FailSafeSupervisor:
    """
    Supervisor system implementing all fail-safe checks from aufgabenliste.md
    Monitors PG-ES optimization in real-time and alerts on anomalies
    """
    
    def __init__(self, config):
        self.config = config
        self.logger = logging.getLogger(__name__)
        
        # Alert tracking
        self.alerts: List[SupervisorAlert] = []
        self.alert_counts = {level: 0 for level in AlertLevel}
        
        # Historical data for trend analysis
        self.fitness_history: List[float] = []
        self.pg_loss_history: List[float] = []
        self.es_fitness_history: List[float] = []
        self.parameter_history: List[Dict] = []
        self.safety_violation_history: List[int] = []
        
        # Anomaly detection thresholds
        self.fitness_variance_threshold = 10.0
        self.parameter_drift_threshold = 0.1
        self.safety_violation_rate_threshold = 0.05  # 5% max violation rate
        
        # Emergency freeze flag
        self.system_frozen = False
        self.freeze_reason = ""
        
        # PG-ES balance tracking
        self.pg_contribution_history = []
        self.es_contribution_history = []
        self.balance_target = 0.7  # 70% PG, 30% ES from config
        
        self.logger.info("Fail-Safe Supervisor System initialized")
    
    def check_all_systems(self, 
                         simulation_state, 
                         pg_metrics: Dict, 
                         es_metrics: Dict, 
                         domain_rand_state: Dict) -> List[SupervisorAlert]:
        """
        Master check function - runs all fail-safe checks
        Returns list of alerts generated
        """
        
        if self.system_frozen:
            return [SupervisorAlert(
                timestamp=time.time(),
                level=AlertLevel.EMERGENCY,
                category="SYSTEM_FROZEN",
                message=f"System is frozen: {self.freeze_reason}",
                requires_intervention=True
            )]
        
        new_alerts = []
        
        # Run all individual checks
        new_alerts.extend(self._check_realism(simulation_state, pg_metrics, es_metrics))
        new_alerts.extend(self._check_domain_randomization(domain_rand_state))
        new_alerts.extend(self._check_safety_constraints(simulation_state))
        new_alerts.extend(self._check_pg_es_balance(pg_metrics, es_metrics))
        new_alerts.extend(self._check_outliers_overfitting(pg_metrics, es_metrics))
        new_alerts.extend(self._check_sim2real_deviation())
        new_alerts.extend(self._check_extreme_errors(simulation_state))
        
        # Add to alert history
        self.alerts.extend(new_alerts)
        for alert in new_alerts:
            self.alert_counts[alert.level] += 1
        
        # Check for emergency freeze conditions
        self._check_emergency_freeze_conditions(new_alerts)
        
        return new_alerts

    # --- Lightweight status APIs expected by trainer/tests ---
    def get_status(self) -> Dict[str, Any]:
        """Return a brief current status for dashboard updates."""
        return {
            'total_alerts': len(self.alerts),
            'system_frozen': self.system_frozen,
            'freeze_reason': self.freeze_reason,
            'alert_counts': {level.name: self.alert_counts[level] for level in self.alert_counts}
        }

    def get_system_status(self) -> Dict[str, Any]:
        """Alias providing a more detailed snapshot (backward compatibility)."""
        return self.get_status()

    def export_alerts_report(self, path: str) -> None:
        """Export a JSON report of alerts."""
        try:
            serializable = []
            for a in self.alerts:
                serializable.append({
                    'timestamp': a.timestamp,
                    'level': a.level.name if isinstance(a.level, AlertLevel) else str(a.level),
                    'category': a.category,
                    'message': a.message,
                    'data': a.data,
                    'requires_intervention': a.requires_intervention,
                })
            with open(path, 'w') as f:
                json.dump(serializable, f, indent=2)
        except Exception:
            pass
    
    def _check_realism(self, sim_state, pg_metrics: Dict, es_metrics: Dict) -> List[SupervisorAlert]:
        """Check 1: Realismus-Check (Mutationsparameter & Fitness)"""
        alerts = []
        
        # Check mutation parameter ranges
        if 'mutation_strength' in es_metrics:
            sigma = es_metrics['mutation_strength']
            if sigma > 1.0:  # Too high mutation
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.WARNING,
                    category="REALISM_CHECK",
                    message=f"Mutation strength too high: {sigma:.3f} > 1.0",
                    data={"mutation_strength": sigma}
                ))
            elif sigma < 0.001:  # Too low mutation
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.WARNING,
                    category="REALISM_CHECK",
                    message=f"Mutation strength too low: {sigma:.6f} < 0.001",
                    data={"mutation_strength": sigma}
                ))
        
        # Check fitness realism
        if 'fitness' in es_metrics:
            fitness = es_metrics['fitness']
            
            # Fitness should be bounded and reasonable
            if abs(fitness) > 1000:
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.CRITICAL,
                    category="REALISM_CHECK",
                    message=f"Unrealistic fitness value: {fitness}",
                    data={"fitness": fitness},
                    requires_intervention=True
                ))
            
            # Check for fitness variance explosion
            self.fitness_history.append(fitness)
            if len(self.fitness_history) > 100:
                self.fitness_history.pop(0)
                variance = np.var(self.fitness_history)
                if variance > self.fitness_variance_threshold:
                    alerts.append(SupervisorAlert(
                        timestamp=time.time(),
                        level=AlertLevel.WARNING,
                        category="REALISM_CHECK",
                        message=f"High fitness variance: {variance:.2f}",
                        data={"fitness_variance": variance}
                    ))
        
        # Check physical parameter realism
        if hasattr(sim_state, 'temperature'):
            temp = sim_state.temperature
            if temp < -50 or temp > 100:  # Beyond realistic range
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.CRITICAL,
                    category="REALISM_CHECK",
                    message=f"Unrealistic temperature: {temp:.1f}°C",
                    data={"temperature": temp}
                ))
        
        return alerts
    
    def _check_domain_randomization(self, domain_rand_state: Dict) -> List[SupervisorAlert]:
        """Check 2: Domain Randomization Monitor (Drift & Extremfälle)"""
        alerts = []
        
        # Check for excessive randomization
        if 'noise_levels' in domain_rand_state:
            noise_levels = domain_rand_state['noise_levels']
            
            for param, noise in noise_levels.items():
                if noise > 0.5:  # 50% noise is probably too much
                    alerts.append(SupervisorAlert(
                        timestamp=time.time(),
                        level=AlertLevel.WARNING,
                        category="DOMAIN_RANDOMIZATION",
                        message=f"High noise level for {param}: {noise:.3f}",
                        data={"parameter": param, "noise_level": noise}
                    ))
        
        # Check for drift in randomization parameters
        if 'parameter_drift' in domain_rand_state:
            drift = domain_rand_state['parameter_drift']
            if abs(drift) > self.parameter_drift_threshold:
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.WARNING,
                    category="DOMAIN_RANDOMIZATION",
                    message=f"Parameter drift detected: {drift:.4f}",
                    data={"drift": drift}
                ))
        
        # Check for extreme randomization events
        if 'extreme_events' in domain_rand_state:
            extreme_count = domain_rand_state['extreme_events']
            if extreme_count > 10:  # Too many extreme events
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.WARNING,
                    category="DOMAIN_RANDOMIZATION",
                    message=f"Too many extreme events: {extreme_count}",
                    data={"extreme_events": extreme_count}
                ))
        
        return alerts
    
    def _check_safety_constraints(self, sim_state) -> List[SupervisorAlert]:
        """Check 3: Safety-Constraints Code-Level enforced"""
        alerts = []
        
        # Track safety violations
        violation_count = len(getattr(sim_state, 'safety_violations', []))
        self.safety_violation_history.append(violation_count)
        
        # Check immediate violations
        if violation_count > 0:
            alerts.append(SupervisorAlert(
                timestamp=time.time(),
                level=AlertLevel.CRITICAL,
                category="SAFETY_CONSTRAINTS",
                message=f"Active safety violations: {violation_count}",
                data={"violations": getattr(sim_state, 'safety_violations', [])},
                requires_intervention=True
            ))
        
        # Check violation rate over time
        if len(self.safety_violation_history) > 100:
            self.safety_violation_history.pop(0)
            violation_rate = sum(1 for v in self.safety_violation_history if v > 0) / len(self.safety_violation_history)
            
            if violation_rate > self.safety_violation_rate_threshold:
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.CRITICAL,
                    category="SAFETY_CONSTRAINTS",
                    message=f"High safety violation rate: {violation_rate:.3f}",
                    data={"violation_rate": violation_rate},
                    requires_intervention=True
                ))
        
        # Check degradation factor
        if hasattr(sim_state, 'degradation_factor'):
            degradation = sim_state.degradation_factor
            if degradation < 0.5:  # Component severely degraded
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.CRITICAL,
                    category="SAFETY_CONSTRAINTS",
                    message=f"Severe component degradation: {degradation:.3f}",
                    data={"degradation_factor": degradation}
                ))
        
        return alerts
    
    def _check_pg_es_balance(self, pg_metrics: Dict, es_metrics: Dict) -> List[SupervisorAlert]:
        """Check 4: PG/ES-Balance-Health-Check aktiv"""
        alerts = []
        
        # Track contributions
        pg_contrib = pg_metrics.get('contribution', 0.0)
        es_contrib = es_metrics.get('contribution', 0.0)
        
        self.pg_contribution_history.append(pg_contrib)
        self.es_contribution_history.append(es_contrib)
        
        # Keep history manageable
        if len(self.pg_contribution_history) > 1000:
            self.pg_contribution_history.pop(0)
            self.es_contribution_history.pop(0)
        
        # Check current balance
        total_contrib = pg_contrib + es_contrib
        if total_contrib > 0:
            pg_ratio = pg_contrib / total_contrib
            
            # Check if balance is too far from target
            balance_deviation = abs(pg_ratio - self.balance_target)
            if balance_deviation > 0.3:  # 30% deviation from target
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.WARNING,
                    category="PG_ES_BALANCE",
                    message=f"PG-ES balance deviation: {balance_deviation:.3f}",
                    data={"pg_ratio": pg_ratio, "target": self.balance_target}
                ))
        
        # Check for one method dominating completely
        if len(self.pg_contribution_history) > 50:
            recent_pg = np.mean(self.pg_contribution_history[-50:])
            recent_es = np.mean(self.es_contribution_history[-50:])
            
            if recent_pg == 0 and recent_es > 0:
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.WARNING,
                    category="PG_ES_BALANCE",
                    message="PG contribution is zero - algorithm not working",
                    data={"pg_contribution": recent_pg}
                ))
            elif recent_es == 0 and recent_pg > 0:
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.WARNING,
                    category="PG_ES_BALANCE",
                    message="ES contribution is zero - algorithm not working",
                    data={"es_contribution": recent_es}
                ))
        
        return alerts
    
    def _check_outliers_overfitting(self, pg_metrics: Dict, es_metrics: Dict) -> List[SupervisorAlert]:
        """Check 5: Outlier & Overfitting Watchdog"""
        alerts = []
        
        # Check PG loss progression
        if 'loss' in pg_metrics:
            loss = pg_metrics['loss']
            self.pg_loss_history.append(loss)
            
            if len(self.pg_loss_history) > 100:
                self.pg_loss_history.pop(0)
                
                # Check for loss explosion
                if loss > 100 * np.mean(self.pg_loss_history[:-1]):
                    alerts.append(SupervisorAlert(
                        timestamp=time.time(),
                        level=AlertLevel.WARNING,
                        category="OUTLIER_OVERFITTING",
                        message=f"PG loss explosion: {loss:.6f}",
                        data={"loss": loss}
                    ))
                
                # Check for overfitting (loss plateau at very low values)
                if len(self.pg_loss_history) > 50:
                    recent_losses = self.pg_loss_history[-50:]
                    if np.std(recent_losses) < 1e-8 and np.mean(recent_losses) < 1e-6:
                        alerts.append(SupervisorAlert(
                            timestamp=time.time(),
                            level=AlertLevel.WARNING,
                            category="OUTLIER_OVERFITTING",
                            message="Possible PG overfitting detected",
                            data={"loss_std": np.std(recent_losses)}
                        ))
        
        # Check ES population diversity
        if 'population_diversity' in es_metrics:
            diversity = es_metrics['population_diversity']
            if diversity < 0.01:  # Very low diversity
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.WARNING,
                    category="OUTLIER_OVERFITTING",
                    message=f"Low ES population diversity: {diversity:.6f}",
                    data={"diversity": diversity}
                ))
        
        return alerts
    
    def _check_sim2real_deviation(self) -> List[SupervisorAlert]:
        """Check 6: Sim-to-Real Abweichungs-Indikator"""
        alerts = []
        
        # This is a placeholder - real implementation would need
        # comparison with real hardware data when available
        
        # Check for indicators of potential sim2real gap
        if len(self.fitness_history) > 200:
            # Look for suspiciously perfect performance
            recent_fitness = self.fitness_history[-100:]
            if np.std(recent_fitness) < 0.001 and np.mean(recent_fitness) > 0.95:
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.WARNING,
                    category="SIM2REAL_DEVIATION",
                    message="Suspiciously perfect performance - check sim realism",
                    data={"fitness_std": np.std(recent_fitness)}
                ))
        
        return alerts
    
    def _check_extreme_errors(self, sim_state) -> List[SupervisorAlert]:
        """Check 7: Anomalie-Freeze bei Extrem-Fehlern"""
        alerts = []
        
        # Check for NaN or infinite values
        state_vector = getattr(sim_state, 'get_state_vector', lambda: [])()
        if len(state_vector) > 0:
            if np.any(np.isnan(state_vector)) or np.any(np.isinf(state_vector)):
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.EMERGENCY,
                    category="EXTREME_ERRORS",
                    message="NaN or Inf detected in simulation state",
                    data={"state_has_nan": bool(np.any(np.isnan(state_vector))),
                          "state_has_inf": bool(np.any(np.isinf(state_vector)))},
                    requires_intervention=True
                ))
        
        # Check for extreme temperature conditions that could damage hardware
        if hasattr(sim_state, 'temperature'):
            temp = sim_state.temperature
            if temp > 200 or temp < -100:  # Extreme conditions
                alerts.append(SupervisorAlert(
                    timestamp=time.time(),
                    level=AlertLevel.EMERGENCY,
                    category="EXTREME_ERRORS",
                    message=f"Extreme temperature condition: {temp:.1f}°C",
                    data={"temperature": temp},
                    requires_intervention=True
                ))
        
        return alerts
    
    def _check_emergency_freeze_conditions(self, new_alerts: List[SupervisorAlert]):
        """Check if system should be frozen due to critical conditions"""
        
        # Count critical and emergency alerts
        critical_count = sum(1 for alert in new_alerts if alert.level == AlertLevel.CRITICAL)
        emergency_count = sum(1 for alert in new_alerts if alert.level == AlertLevel.EMERGENCY)
        
        # Freeze conditions
        if emergency_count > 0:
            self.system_frozen = True
            self.freeze_reason = f"Emergency alerts: {emergency_count}"
            self.logger.error(f"SYSTEM FROZEN: {self.freeze_reason}")
        
        elif critical_count > 5:  # Too many critical alerts at once
            self.system_frozen = True
            self.freeze_reason = f"Multiple critical alerts: {critical_count}"
            self.logger.error(f"SYSTEM FROZEN: {self.freeze_reason}")
        
        # Check for intervention required
        intervention_alerts = [a for a in new_alerts if a.requires_intervention]
        if len(intervention_alerts) > 0:
            self.logger.error(f"INTERVENTION REQUIRED: {len(intervention_alerts)} alerts")
    
    def _json_safe(self, obj: Any) -> Any:
        """Recursively convert supervisor data into JSON-serializable structures."""
        try:
            import numpy as _np  # pragma: no cover - optional dependency during tests
            if isinstance(obj, _np.ndarray):
                return obj.tolist()
            if isinstance(obj, _np.generic):
                return obj.item()
        except Exception:
            pass

        if isinstance(obj, Enum):
            return getattr(obj, "name", getattr(obj, "value", str(obj)))

        try:
            from dataclasses import asdict as _asdict, is_dataclass as _is_dataclass
            if _is_dataclass(obj):
                return self._json_safe(_asdict(obj))
        except Exception:
            pass

        if isinstance(obj, dict):
            safe_dict = {}
            for key, value in obj.items():
                if isinstance(key, Enum):
                    safe_key = getattr(key, "name", getattr(key, "value", str(key)))
                elif isinstance(key, (str, int, float, bool)) or key is None:
                    safe_key = key
                else:
                    safe_key = str(key)
                safe_dict[safe_key] = self._json_safe(value)
            return safe_dict

        if isinstance(obj, (list, tuple, set)):
            return [self._json_safe(item) for item in obj]

        try:
            from pathlib import Path as _Path
            if isinstance(obj, _Path):
                return str(obj)
        except Exception:
            pass

        if hasattr(obj, "__dict__") and not isinstance(obj, (str, bytes)):
            return self._json_safe(vars(obj))

        return obj

    def get_system_status(self) -> Dict[str, Any]:
        """Get current system status for supervisor dashboard"""
        status = {
            "system_frozen": self.system_frozen,
            "freeze_reason": self.freeze_reason,
            "total_alerts": len(self.alerts),
            "alert_counts": self.alert_counts,
            "recent_alerts": self.alerts[-10:] if self.alerts else [],
            "fitness_trend": np.mean(self.fitness_history[-50:]) if len(self.fitness_history) >= 50 else None,
            "safety_violation_rate": np.mean([1 if v > 0 else 0 for v in self.safety_violation_history[-100:]]) if len(self.safety_violation_history) >= 100 else 0,
        }
        return self._json_safe(status)
    
    def unfreeze_system(self, reason: str):
        """Manually unfreeze system (supervisor intervention)"""
        self.system_frozen = False
        self.freeze_reason = ""
        self.logger.info(f"System unfrozen by supervisor: {reason}")
    
    def export_alerts_report(self, filepath: str):
        """Export detailed alerts report for analysis"""
        report = {
            "timestamp": time.time(),
            "system_status": self.get_system_status(),
            "all_alerts": [
                {
                    "timestamp": alert.timestamp,
                    "level": alert.level.value,
                    "category": alert.category,
                    "message": alert.message,
                    "data": alert.data,
                    "requires_intervention": alert.requires_intervention
                }
                for alert in self.alerts
            ]
        }
        
        with open(filepath, 'w') as f:
            json.dump(self._json_safe(report), f, indent=2)
        
        self.logger.info(f"Alerts report exported to {filepath}")
